---
title: "KJE Hickman's Academic History"
pagetitle: "CV"
author: "Jo Hickman"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_depth: 4
    toc_float: yes
TOC: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Education

#### MIT-WHOI Joint Program

* Expected 2028.  __Biological Oceanography Ph.D.__
  + NSF Graduate Research Fellow
  + Graduate Certificate in Science, Technology and Policy
<br><br>

#### Utah Valley University

* 2023.  __Bioinformatics B.S.__
  + _summa cum laude_
  + Minor in Biology
  + Minor in Computer Science
<br><br>
* 2018.  __Integrated Studies B.S.__
  + _summa cum laude_
  + Emphasis in Earth Science
  + Emphasis in Peace & Justice Studies
<br><br>
* 2018.  __Philosophy B.A.__
  + _summa cum laude_


## Publications

* Wainwright, B. J., Millar, T., Bowen, L., Hickman, K. J. E., Lee, J. N., Yeo, Z. Y., & Zahn, G. (2023). __“The core mangrove microbiome reveals shared taxa potentially involved in nutrient cycling and promoting host survival.”__ _Environmental Microbiome_ __18__, 47. [https://doi.org/10.1186/s40793-023-00499-5](https://doi.org/10.1186/s40793-023-00499-5)

* Hickman, K. J. E. (2022) __“The Integral Role of the Coastal Microbiome in Mangrove Conservation.”__ _United Nations’ First Academic Conference on the Sustainable Development Goals “Why It Matters” Conference Proceedings_. Orem, Utah, 5-7 October, 2022, pp. 475 - 493. [https://www.uvu.edu/global/docs/wim22/wim22-publication-v2.pdf](https://www.uvu.edu/global/docs/wim22/wim22-publication-v2.pdf)

* (in prep for _Journal of Biogeography_) Wainwright, B., Leon, J, Hickman K. J. E., Vilela, E., Caldwell, E., Aimone, B., Bischoff, P., Morelli, M., & Zahn, G. __“Cryptic dispersal barriers affect some host-associated marine bacteria across Wallace's Line.”__

* (in prep for _Environmental Earth Sciences_) Hickman, K. J. E., Rawson, C., Batte, L., Seawolf, S., Larsen, T., Cadet, E. __Trace Metal Concentrations in Upland and Wetland Sediments of Utah Lake__. National Science Foundation, Utah Lake Project.


## Research Projects

* Alexander, H., __Hickman, K. J. E.__, Krinos, A. _Metatranscriptomics of Microbial Eukaryotes in the Open Ocean_. 

*	__Hickman, K. J. E.__, Leon, J., Zahn, G. (2022) _Metagenomic Tools for Microbiome Analyses in Model versus Non-Model Systems_. 

* Bingham, C., __Hickman, K. J. E.__, Leon, J., Pimentel, I., Garcia, J., Rawson, C. (2022) _A Toxic Legacy: Nuclear Pollution in the Navajo Nation_. Oxford University, Map the System. 

* Cadet, E., __Hickman, K. J. E.__ (2022). _Trace Metal Concentrations in Fish and Water of Utah Lake_. National Science Foundation, Utah Lake Project.

* DeVynck, D., __Hickman, K. J. E.__ (2019). _Permaculture Plant Guilds in Traditional Furrows_. Orem Permaculture Project. 

*	__Hickman, K. J. E.__ (2018). _Agriculture in Guinea-Bissau: The Viability of Agroforestry with Cacao and Cashew_. Utah Valley University Honors Program.

* Emerman, S. H., __Hickman, K. J. E.__, Pacheco, W., Patterson, C., and Tolman, A. (2018). _Estimation of the Stream Water Quality Baseline in the Henry Mountains, Utah_. Utah Valley University.

* __Hickman, K. J. E.__, Minch, M. (2017). _PeaceTech and the Future of Peacebuilding and Sustainable Development_. Utah Valley University.

* Hansen, J., __Hickman, K. J. E.__ (2017). _Tracking Intuition on the Trolley Problem_. Utah Valley University.


## Teaching & Instruction

* 2022. Co-instructor, Microbiome Bootcamp, Washington State University
    + DADA2 Workflow: Data Analysis and Visualization
<br><br>

* 2022. Co-instructor, "Map the System" Workshop Series, Utah Valley University
  + Systems Thinking & Equity-Centered Design
<br><br>

*	2017 - 2020. ELL Teacher, Macote Entrepreneur Center, Bissau, Guinea-Bissau
    +	ENG Level 0
    + ENG Level 1
    + ENG Level 2
    + ENG Advanced Literature
<br><br>

*	2017 - 2018. Instructional Assistant, Principles of Formal Logic, Utah Valley University, Orem, UT
    +	PHIL 1250: Introduction to Logic and Critical Thinking
<br><br>

*	2016 - 2018. Instructional Assistant, Utah Valley University, Orem, UT
    +	PHIL 2050: Ethics & Values


## Leadership & Organizing

* 2022 – 2023. __Systems and Design Fellow__,  Center for Social Impact
<br>
* 2022 – 2023. __Treasurer__,  Women in Physical Sciences Club 
<br>
* 2021 – 2023. __Academic Library Supervisor__,  Fulton Library
<br>
* 2021 – 2023. __Organizer__,  Girls Who Code Chapter
<br>
* 2021 – 2022. __Executive News Director__,  The UVU Review
<br>
* 2018. __Integrated Studies Department Representative__,  UVU Student Association
<br>
*	2017 – 2019. __Editor-in-Chief__,  Sophia: Undergraduate Journal of Philosophy
<br>
* 2017. __Philosophy Department Representative__,  UVU Student Association
<br>
* 2017. __President__, UVU Peace and Justice Club
<br>


## Honors & Awards

*	2023. Graduate Research Fellowship Program, National Science Foundation
<br>
*	2023. Biology Student Excellence Award for Research, Utah Valley University
<br>
*	2022. Excellence in Undergraduate Research, University of Oxford
<br>
*	2022. President’s Scholarship Ball “Outstanding Student” Highlight, Utah Valley University
<br>
*	2022. Biology Department “Student of the Year” nominee, Utah Valley University
<br>
*	2018. College of Humanities and Social Science “Dean’s Choice” award, Utah Valley University
<br>
*	2018. Philosophy Department “Student of the Year” award, Utah Valley University
<br>
*	2017 – 2023. Honors Program, Utah Valley University
<br>
*	2016 – 2023. Dean’s List, Utah Valley University

<br><br>
